openapi: 3.0.3
# Common schemas used across multiple domains

components:
  schemas:
    BacktestRequest:
      type: object
      required:
        - strategyId
        - startDate
        - endDate
        - instruments
        - initialCapital
      properties:
        strategyId:
          type: string
          format: uuid
          description: ID of the strategy to backtest
        strategyConfig:
          type: object
          description: Configuration parameters for the strategy
          additionalProperties: true
        startDate:
          type: string
          format: date
          description: Start date for the backtest
        endDate:
          type: string
          format: date
          description: End date for the backtest
        instruments:
          type: array
          description: List of instruments to include in the backtest
          items:
            type: string
        initialCapital:
          type: number
          format: float
          description: Initial capital for the backtest
          minimum: 0
        commission:
          type: number
          format: float
          description: Commission rate per trade
          default: 0.001
          minimum: 0
        slippage:
          type: number
          format: float
          description: Slippage model parameter
          default: 0.0005
          minimum: 0
        dataInterval:
          type: string
          enum: [1m, 5m, 15m, 30m, 1h, 4h, 1d, 1w, 1mo]
          default: 1d
          description: Data interval for the backtest
        name:
          type: string
          description: Custom name for the backtest

    BacktestCreationResponse:
      type: object
      required:
        - backtestId
        - status
      properties:
        backtestId:
          type: string
          format: uuid
          description: ID of the created backtest
        status:
          type: string
          enum: [pending, running]
          description: Status of the backtest
        estimatedCompletionTime:
          type: string
          format: date-time
          description: Estimated time for backtest completion

    BacktestSummary:
      type: object
      required:
        - backtestId
        - strategyId
        - status
        - createdAt
      properties:
        backtestId:
          type: string
          format: uuid
          description: ID of the backtest
        name:
          type: string
          description: Custom name of the backtest
        strategyId:
          type: string
          format: uuid
          description: ID of the strategy used
        strategyName:
          type: string
          description: Name of the strategy
        status:
          type: string
          enum: [pending, running, completed, failed]
          description: Status of the backtest
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the backtest was created
        completedAt:
          type: string
          format: date-time
          description: Timestamp when the backtest completed (if applicable)
        startDate:
          type: string
          format: date
          description: Start date of the backtest
        endDate:
          type: string
          format: date
          description: End date of the backtest
        instruments:
          type: array
          items:
            type: string
          description: List of instruments included in the backtest
        metrics:
          $ref: '#/components/schemas/PerformanceMetricsSummary'

    BacktestDetail:
      allOf:
        - $ref: '#/components/schemas/BacktestSummary'
        - type: object
          properties:
            strategyConfig:
              type: object
              description: Configuration used for the strategy
              additionalProperties: true
            initialCapital:
              type: number
              format: float
              description: Initial capital used for the backtest
            commission:
              type: number
              format: float
              description: Commission rate used
            slippage:
              type: number
              format: float
              description: Slippage model parameter used
            dataInterval:
              type: string
              enum: [1m, 5m, 15m, 30m, 1h, 4h, 1d, 1w, 1mo]
              description: Data interval used for the backtest
            errorMessage:
              type: string
              description: Error message if the backtest failed

    PerformanceMetricsSummary:
      type: object
      description: Summary of key performance metrics
      properties:
        totalReturn:
          type: number
          format: float
          description: Total return percentage
        annualizedReturn:
          type: number
          format: float
          description: Annualized return percentage
        sharpeRatio:
          type: number
          format: float
          description: Sharpe ratio
        maxDrawdown:
          type: number
          format: float
          description: Maximum drawdown percentage

    PerformanceMetrics:
      allOf:
        - $ref: '#/components/schemas/PerformanceMetricsSummary'
        - type: object
          properties:
            sortinoRatio:
              type: number
              format: float
              description: Sortino ratio
            calmarRatio:
              type: number
              format: float
              description: Calmar ratio
            volatility:
              type: number
              format: float
              description: Annualized volatility
            beta:
              type: number
              format: float
              description: Beta relative to benchmark
            alpha:
              type: number
              format: float
              description: Alpha (annualized)
            winRate:
              type: number
              format: float
              description: Winning trades percentage
            profitFactor:
              type: number
              format: float
              description: Profit factor
            maxConsecutiveWins:
              type: integer
              description: Maximum consecutive winning trades
            maxConsecutiveLosses:
              type: integer
              description: Maximum consecutive losing trades
            averageWin:
              type: number
              format: float
              description: Average winning trade percentage
            averageLoss:
              type: number
              format: float
              description: Average losing trade percentage
            averageTradeLength:
              type: number
              format: float
              description: Average trade duration in days
            totalTrades:
              type: integer
              description: Total number of trades
            exposureTime:
              type: number
              format: float
              description: Percentage of time with market exposure

    Trade:
      type: object
      required:
        - tradeId
        - instrument
        - entryDate
        - entryPrice
        - direction
      properties:
        tradeId:
          type: string
          format: uuid
          description: Unique ID for the trade
        instrument:
          type: string
          description: Instrument identifier
        entryDate:
          type: string
          format: date-time
          description: Entry timestamp
        entryPrice:
          type: number
          format: float
          description: Entry price
        entryReason:
          type: string
          description: Signal or reason for entry
        exitDate:
          type: string
          format: date-time
          description: Exit timestamp (if closed)
        exitPrice:
          type: number
          format: float
          description: Exit price (if closed)
        exitReason:
          type: string
          description: Signal or reason for exit
        direction:
          type: string
          enum: [long, short]
          description: Trade direction
        quantity:
          type: number
          format: float
          description: Trade size/quantity
        profitLoss:
          type: number
          format: float
          description: Profit/loss amount (if closed)
        profitLossPercent:
          type: number
          format: float
          description: Profit/loss percentage (if closed)
        commission:
          type: number
          format: float
          description: Commission paid

    Strategy:
      type: object
      required:
        - strategyId
        - name
        - type
      properties:
        strategyId:
          type: string
          format: uuid
          description: Unique ID for the strategy
        name:
          type: string
          description: Strategy name
        description:
          type: string
          description: Strategy description
        type:
          type: string
          enum: [built-in, custom]
          description: Strategy type
        category:
          type: string
          enum: [trend-following, mean-reversion, momentum, statistical-arbitrage, market-making, options, machine-learning]
          description: Strategy category
        parameters:
          type: array
          description: Available strategy parameters
          items:
            type: object
            required:
              - name
              - type
            properties:
              name:
                type: string
                description: Parameter name
              type:
                type: string
                enum: [integer, float, boolean, string, enum]
                description: Parameter data type
              description:
                type: string
                description: Parameter description
              default:
                description: Default value
              min:
                description: Minimum value (for numeric types)
              max:
                description: Maximum value (for numeric types)
              options:
                type: array
                description: Available options (for enum type)
                items:
                  type: string
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp (for custom strategies)
        source:
          type: string
          description: Strategy code or logic (for custom strategies)

    StrategyCreationRequest:
      type: object
      required:
        - name
        - source
      properties:
        name:
          type: string
          description: Strategy name
        description:
          type: string
          description: Strategy description
        source:
          type: string
          description: Strategy code or logic in the platform's supported language
        parameters:
          type: array
          description: Strategy parameters definition
          items:
            type: object
            required:
              - name
              - type
            properties:
              name:
                type: string
                description: Parameter name
              type:
                type: string
                enum: [integer, float, boolean, string, enum]
                description: Parameter data type
              description:
                type: string
                description: Parameter description
              default:
                description: Default value
              min:
                description: Minimum value (for numeric types)
              max:
                description: Maximum value (for numeric types)
              options:
                type: array
                description: Available options (for enum type)
                items:
                  type: string

    Instrument:
      type: object
      required:
        - id
        - symbol
        - name
        - type
      properties:
        id:
          type: string
          description: Unique identifier for the instrument
        symbol:
          type: string
          description: Trading symbol
        name:
          type: string
          description: Full name
        type:
          type: string
          enum: [stock, etf, forex, crypto, futures, options]
          description: Instrument type
        exchange:
          type: string
          description: Exchange where the instrument is traded
        currency:
          type: string
          description: Base currency
        dataAvailable:
          type: object
          properties:
            startDate:
              type: string
              format: date
              description: Earliest date with available data
            endDate:
              type: string
              format: date
              description: Latest date with available data
            intervals:
              type: array
              items:
                type: string
                enum: [1m, 5m, 15m, 30m, 1h, 4h, 1d, 1w, 1mo]
              description: Available data intervals
        meta:
          type: object
          description: Additional metadata
          additionalProperties: true

    InstrumentData:
      type: object
      required:
        - instrumentId
        - interval
        - data
      properties:
        instrumentId:
          type: string
          description: Instrument identifier
        symbol:
          type: string
          description: Instrument symbol
        interval:
          type: string
          enum: [1m, 5m, 15m, 30m, 1h, 4h, 1d, 1w, 1mo]
          description: Data interval
        startDate:
          type: string
          format: date
          description: Start date of the data
        endDate:
          type: string
          format: date
          description: End date of the data
        data:
          type: array
          items:
            type: object
            required:
              - timestamp
              - open
              - high
              - low
              - close
              - volume
            properties:
              timestamp:
                type: string
                format: date-time
                description: Bar timestamp
              open:
                type: number
                format: float
                description: Opening price
              high:
                type: number
                format: float
                description: Highest price
              low:
                type: number
                format: float
                description: Lowest price
              close:
                type: number
                format: float
                description: Closing price
              volume:
                type: number
                format: float
                description: Trading volume
              adjustedClose:
                type: number
                format: float
                description: Adjusted closing price

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
        details:
          type: object
          description: Additional error details
          additionalProperties: true