openapi: 3.0.3
# Instruments domain - contains all instrument-related paths and components

paths:
  /instruments:
    get:
      summary: List available financial instruments
      description: Returns a list of financial instruments available for backtesting
      operationId: listInstruments
      tags:
        - instruments
      parameters:
        - name: type
          in: query
          description: Filter instruments by type
          schema:
            type: string
            enum: [stock, etf, forex, crypto, futures, options]
        - name: exchange
          in: query
          description: Filter instruments by exchange
          schema:
            type: string
        - name: search
          in: query
          description: Search term for finding instruments
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of results to return
          schema:
            type: integer
            default: 50
            maximum: 200
        - name: offset
          in: query
          description: Number of results to skip
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of instruments
          content:
            application/json:
              schema:
                type: object
                properties:
                  instruments:
                    type: array
                    items:
                      $ref: './common.yaml#/components/schemas/Instrument'
                  total:
                    type: integer
                    description: Total number of instruments matching criteria
                  limit:
                    type: integer
                    description: Limit used for pagination
                  offset:
                    type: integer
                    description: Offset used for pagination
        '401':
          description: Unauthorized

  /instruments/{instrumentId}/data:
    get:
      summary: Get historical data for an instrument
      description: Returns historical price and volume data for a specific instrument
      operationId: getInstrumentData
      tags:
        - instruments
      parameters:
        - name: instrumentId
          in: path
          required: true
          description: ID of the instrument
          schema:
            type: string
        - name: startDate
          in: query
          required: true
          description: Start date for historical data (ISO format)
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          description: End date for historical data (ISO format)
          schema:
            type: string
            format: date
        - name: interval
          in: query
          description: Data interval
          schema:
            type: string
            enum: [1m, 5m, 15m, 30m, 1h, 4h, 1d, 1w, 1mo]
            default: 1d
      responses:
        '200':
          description: Historical instrument data
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/InstrumentData'
        '401':
          description: Unauthorized
        '404':
          description: Instrument not found
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Error'