openapi: 3.0.3
info:
  title: Quant Application Backtest API
  description: API for backtesting trading strategies in a quantitative finance application
  version: 1.0.0
  contact:
    name: API Support
    email: support@quantapp.example.com
servers:
  - url: https://api.quantapp.example.com/v1
    description: Production server
  - url: https://staging-api.quantapp.example.com/v1
    description: Staging server
  - url: http://localhost:8080/v1
    description: Local development

# Tags defined across all domains
tags:
  - name: backtest
    description: Endpoints for running and managing backtests
  - name: strategies
    description: Trading strategy management
  - name: instruments
    description: Financial instruments data
  - name: results
    description: Backtest results and analytics

# Security schemes
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - bearerAuth: []
  - apiKeyAuth: []

# References to paths defined in domain-specific files
paths:
  # Backtest paths (imported from backtest.yaml)
  /backtest:
    $ref: './backtest.yaml#/paths/~1backtest'
  /backtest/{backtestId}:
    $ref: './backtest.yaml#/paths/~1backtest~1{backtestId}'
  /backtest/{backtestId}/results:
    $ref: './backtest.yaml#/paths/~1backtest~1{backtestId}~1results'

  # Strategy paths (imported from strategies.yaml)
  /strategies:
    $ref: './strategies.yaml#/paths/~1strategies'
  /strategies/{strategyId}:
    $ref: './strategies.yaml#/paths/~1strategies~1{strategyId}'

  # Instrument paths (imported from instruments.yaml)
  /instruments:
    $ref: './instruments.yaml#/paths/~1instruments'
  /instruments/{instrumentId}/data:
    $ref: './instruments.yaml#/paths/~1instruments~1{instrumentId}~1data'