spring:
  application:
    name: quant-api

server:
  port: 8080
  shutdown: graceful

# Logging configuration
logging:
  level:
    root: INFO
    com.quantz: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO



