# Grafana Helm chart values for local development
# Path: helm-values/grafana-values.yaml

## Grafana image version
## ref: https://hub.docker.com/r/grafana/grafana/tags/
##
image:
  repository: grafana/grafana
  tag: 9.3.6

## Admin credentials
adminUser: admin
adminPassword: admin

## Configure data sources for observability stack
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: 5s
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        jsonData:
          maxLines: 1000
      - name: Tempo
        type: tempo
        url: http://tempo.monitoring.svc.cluster.local:3100
        access: proxy
        jsonData:
          nodeGraph:
            enabled: true
          tracesToLogs:
            datasourceUid: 'loki'
            tags: ['job', 'instance', 'pod']
            mappedTags: [{ key: 'service.name', value: 'service' }]
            spanStartTimeShift: '1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: true
          serviceMap:
            datasourceUid: 'prometheus'

## Configure dashboards
dashboards:
  default:
    # Spring Boot dashboard
    spring-boot:
      gnetId: 11955  # Micrometer Spring Boot 2.1 dashboard
      revision: 1
      datasource: Prometheus
    # Kafka dashboard
    kafka:
      gnetId: 7589  # Kafka overview
      revision: 5
      datasource: Prometheus
    # JVM dashboard
    jvm:
      gnetId: 4701  # JVM dashboard
      revision: 1
      datasource: Prometheus
    # Kubernetes dashboard
    kubernetes:
      gnetId: 6417  # Kubernetes cluster monitoring
      revision: 1
      datasource: Prometheus
    # PostgreSQL dashboard
    postgresql:
      gnetId: 9628  # PostgreSQL overview
      revision: 7
      datasource: Prometheus
    # Loki Logs dashboard
    loki-logs:
      gnetId: 13639  # Loki logs panel
      revision: 1
      datasource: Loki
    # Tempo Traces dashboard
    tempo-traces:
      gnetId: 17813  # Tempo traces
      revision: 1
      datasource: Tempo
    # Node Exporter dashboard
    node-exporter:
      gnetId: 1860  # Node Exporter Full
      revision: 27
      datasource: Prometheus
    # Spring Boot Observability dashboard (metrics, logs, traces)
    spring-boot-observability:
      gnetId: 17175  # Spring Boot Observability
      revision: 1

## Enable persistence
persistence:
  enabled: true
  size: 2Gi

## Configure resource requests and limits
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

## Configure service
service:
  type: ClusterIP
  port: 80

## Configure Grafana plugins to install
plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel
  - grafana-clock-panel
  - briangann-gauge-panel

## Configure Grafana settings
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/"
  auth:
    disable_login_form: false
  auth.anonymous:
    enabled: true
    org_role: Viewer
  users:
    allow_sign_up: false
    auto_assign_org: true
    auto_assign_org_role: Editor
  dashboards:
    min_refresh_interval: 5s
  security:
    allow_embedding: true

## Enable Ingress (optional)
ingress:
  enabled: false  # For local development, using port forward instead

## Configure sidecar for dashboard and datasource provisioning
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    searchNamespace: ALL
  datasources:
    enabled: true
    label: grafana_datasource
    searchNamespace: ALL

## Configure livenessProbe and readinessProbe
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 10
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 10