## Global parameters
global:
  storageClass: ""

## Bitnami Kafka image version
image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.3.1-debian-11-r0

## Set to true if you want to enable auto-creation of topics
autoCreateTopicsEnable: true
allowPlaintextListener: true
deleteTopicEnable: true

## Number of Kafka brokers
replicaCount: 1

## Disable persistence
persistence:
  enabled: false

## Mount emptyDir volumes for directories that need write access
extraVolumes:
  - name: kafka-data
    emptyDir: {}
  - name: kafka-config
    emptyDir: {}
  - name: kafka-logs
    emptyDir: {}

extraVolumeMounts:
  - name: kafka-data
    mountPath: /bitnami/kafka/data
  - name: kafka-config
    mountPath: /opt/bitnami/kafka/config
  - name: kafka-logs
    mountPath: /opt/bitnami/kafka/logs

## Environment variables for plaintext listener
extraEnvVars:
  - name: ALLOW_PLAINTEXT_LISTENER
    value: "yes"
  - name: KAFKA_CFG_LISTENERS
    value: "PLAINTEXT://:9092"
  - name: KAFKA_ZOOKEEPER_PROTOCOL
    value: "PLAINTEXT"

## Zookeeper configuration
zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: false