# PostgreSQL Helm chart values for local development
# Path: helm-values/postgres-values.yaml

## PostgreSQL image version
## ref: https://hub.docker.com/r/bitnami/postgresql/tags/
##
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 14.5.0-debian-11-r35

## Authentication parameters
## ref: https://github.com/bitnami/bitnami-docker-postgresql#setting-the-root-password-on-first-run
auth:
  enablePostgresUser: true
  postgresPassword: "postgres"
  username: "myapp"
  password: "mypassword"
  database: "myappdb"

## PostgreSQL Primary parameters
primary:
  ## Set the limits and requests
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  ## Persistent Volume Storage configuration
  persistence:
    enabled: true
    # Use a smaller size for local dev
    size: 1Gi

  ## Pod Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

## Database metrics configuration
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s

# Enable audit logs
audit:
  logConnections: true
  logDisconnections: true

# Set reasonable PostgreSQL configuration for development
postgresql:
  extraEnvVars:
    - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
      value: "pg_stat_statements"

  ## PostgreSQL configuration file
  postgresqlConfiguration:
    listenAddresses: "'*'"
    maxConnections: "100"
    sharedBuffers: "128MB"

  # Ensure logs are available for debugging
  postgresqlLogParameters: true