# Spring Boot Application Helm chart values
# Path: helm-values/spring-boot-values.yaml

## Application basic configuration
##
appName: spring-boot-app
replicaCount: 1

## Container image configuration
##
image:
  repository: ${DOCKER_REGISTRY:-localhost}/spring-boot-app
  tag: ${VERSION:-latest}
  pullPolicy: IfNotPresent

## Application service configuration
##
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

## Ingress configuration for Spring Boot app
##
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: spring-app.local
      paths:
        - path: /
          pathType: Prefix

## Resource requirements for Spring Boot app
##
resources:
  requests:
    memory: 512Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 500m

## Spring Boot application properties
##
env:
  # Active Spring profile
  SPRING_PROFILES_ACTIVE: kubernetes
  # Database configuration
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-postgresql.infrastructure.svc.cluster.local:5432/myappdb
  SPRING_DATASOURCE_USERNAME: myapp
  # Kafka configuration
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka.infrastructure.svc.cluster.local:9092
  # Application-specific settings
  APP_SCHEDULER_ENABLED: "true"
  APP_CACHE_TTL: "3600"
  # JVM options
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC"
  # Actuator settings
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  # Tracing configuration for OpenTelemetry
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_TRACING_ENABLED: "true"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo.monitoring.svc.cluster.local:9411/api/v2/spans"
  # Logging configuration for Loki integration
  LOGGING_PATTERN_LEVEL: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

## Secret values, used for sensitive data
##
secrets:
  # Database password
  SPRING_DATASOURCE_PASSWORD: mypassword
  # Other secret values
  APP_SECRET_KEY: changeme

## Actuator probes configuration
##
probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 60
    periodSeconds: 30
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 10

## Configure Prometheus metrics
##
metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 15s
    path: /actuator/prometheus

## Persistence configuration
##
persistence:
  enabled: false  # Typically not needed for stateless Spring Boot apps