# Tempo Helm chart values for local development
# Path: helm-values/tempo-values.yaml

## Tempo image version
## ref: https://hub.docker.com/r/grafana/tempo/tags/
##
image:
  repository: grafana/tempo
  tag: 2.1.1
  pullPolicy: IfNotPresent

## Tempo mode configuration
tempo:
  # Use single binary mode for simplicity in local development
  mode: singleBinary

  # Configure retention
  retention: 24h

  # Configure receivers
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_compact:
          endpoint: 0.0.0.0:6831
    zipkin:
      endpoint: 0.0.0.0:9411
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  # Configure storage
  storage:
    trace:
      backend: local
      local:
        path: /tmp/tempo/traces

  # Metrics config
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write

## Configure storage
storage:
  trace:
    size: 5Gi

## Resource requirements
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

## Service configuration
service:
  type: ClusterIP

## ServiceMonitor configuration for Prometheus
serviceMonitor:
  enabled: true
  interval: 30s
  additionalLabels:
    release: prometheus

## Configure ingestion of application traces
ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

## Configure searching capabilities
search:
  enabled: true

## Configure metastore
metastore:
  type: local

## Configure querier
querier:
  frontend_worker:
    frontend_address: "tempo-query-frontend:9095"

## Configure compactor
compactor:
  compaction:
    block_retention: 24h

## Configure distributor
distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
    zipkin:
      endpoint: 0.0.0.0:9411
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

## Configure server
server:
  http_listen_port: 3200