version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: quantz-marketdata-db
    environment:
      POSTGRES_DB: quantz_market_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - quantz-network

  # Market Data Service
  #marketdata-service:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: quantz-marketdata-service
  #  depends_on:
  #    postgres:
  #      condition: service_healthy
  #  environment:
  #    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/quantz_market_data
  #    - SPRING_DATASOURCE_USERNAME=postgres
  #    - SPRING_DATASOURCE_PASSWORD=postgres
  #    - UPSTOX_AUTH_CLIENT_ID=${UPSTOX_CLIENT_ID}
  #    - UPSTOX_AUTH_CLIENT_SECRET=${UPSTOX_CLIENT_SECRET}
  #    - UPSTOX_AUTH_REDIRECT_URI=http://localhost:8081/api/upstox/auth/callback
  #  ports:
  #    - "8081:8081"
  #  volumes:
  #    - ./logs:/app/logs
  #  restart: unless-stopped
  #  networks:
  #    - quantz-network

networks:
  quantz-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local